apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: teastore-webui-hpa
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: teastore-webui
  targetCPUUtilizationPercentage: 85
